name: Deploy Project
on: push
jobs:
  lint-job:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4      
      - name: Install dependencies
        run: npm ci
      - name: Lint
        run: npm run lint      
  test-job:
    needs: lint-job 
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4      
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
  deployment-job:
    needs: test-job
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4      
      - name: Install dependencies
        run: npm ci
      - name: Build the project
        run: npm run build  
      - name: Deploy
        run: echo "Deployment ...         
