name: Outputting info
on: 
  pull_request: 
    types: [opened, edited]
  workflow_dispatch: 
jobs: 
  info-job:
    runs-on: ubuntu-latest
    steps:
      - name: Output event depails
        run: echo "${{ toJson(github.event)}}"